AWSTemplateFormatVersion: "2010-09-09"
Description: HTTPS/HTTP URL redirector including CDN, HTTPS and the certificate
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Subdomain:
    Type: String
    Default: ''
    Description: The Subdomain to be redirected, can also be empty so that the APEX domain will be redirected
  HostedZoneName:
    Type: String
    Description: Hosted Zone which needs to be in the same AWS account
  RedirectDestinationHostName:
    Type: String
    Description: Hostname of the redirect destination
  RedirectDestinationProtocol:
    Type: String
    Description: Protocol of the redirect destination
  RedirectDestinationPath:
    Type: String
    Description: Path of the redirect destination
    Default: ''

Conditions:
  IsApexRedirect: !Equals [!Ref Subdomain, '']

Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          RoutingRules:
            - RedirectRule:
                HostName: !Ref RedirectDestinationHostName
                Protocol: !Ref RedirectDestinationProtocol
                ReplaceKeyPrefixWith: !Ref RedirectDestinationPath
                HttpRedirectCode: 301

    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref WebsiteBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${WebsiteBucket}/*

    WebsiteCdn:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !Sub ${WebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com
              Id: Origin
              CustomOriginConfig:
                OriginProtocolPolicy: http-only
          DefaultCacheBehavior:
            ForwardedValues:
              QueryString: false
            TargetOriginId: Origin
            ViewerProtocolPolicy: redirect-to-https
          Enabled: true
          Aliases:
            - !If
              - IsApexRedirect
              - !Ref HostedZoneName
              - !Sub ${Subdomain}.${HostedZoneName}
          ViewerCertificate:
            AcmCertificateArn: !Ref WebsiteCertificate
            SslSupportMethod: sni-only
          Logging:
            Bucket: !GetAtt WebsiteCdnLogBucket.DomainName
            IncludeCookies: true

    WebsiteCdnLogBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: BucketOwnerFullControl

    WebsiteCertificate:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName:
          !If
          - IsApexRedirect
          - !Ref HostedZoneName
          - !Sub ${Subdomain}.${HostedZoneName}
        DomainValidationOptions:
          - DomainName:
              !If
              - IsApexRedirect
              - !Ref HostedZoneName
              - !Sub ${Subdomain}.${HostedZoneName}
            ValidationDomain: !Ref HostedZoneName

    DnsCname:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneName: !Sub ${HostedZoneName }.
        RecordSets:
          - Name:
              !If
              - IsApexRedirect
              - !Ref HostedZoneName
              - !Sub ${Subdomain}.${HostedZoneName}
            Type: A
            AliasTarget:
              DNSName: !GetAtt WebsiteCdn.DomainName
              HostedZoneId: Z2FDTNDATAQYW2 # Magic value for CloudFront Hosted Zone
